openshift/appliance

cmd/build.go, pkg/asset/appliance/base_diskimage.go, pkg/asset/data/data_iso.go, pkg/release/release.go
Fix the following issues:
* Error return value of ... is not checked
* unnecessary use of fmt.Sprintf
=> Fix lint errors

cmd/build.go, cmd/debug.go, cmd/main.go, data/scripts/bin/start-local-registry.sh.template, hack/diskimage/test_install_ignition.md, pkg/asset/config/env_config.go, pkg/asset/ignition/bootstrap_ignition.go, pkg/asset/ignition/install_ignition.go, pkg/asset/registry/registriesconf.go, pkg/templates/data.go
As part of the services in install ignition, we need to start a local registry for serving the entire release payload.
In addition, for debugging the process we need two debug flags:
* --debug-bootstrap: stops the flow after bootstrap so install step could be easily tested.
* --debug-install: adds ssh public key to install ignition for connecting during installation.
=> Add local registry to install ignition

Dockerfile.openshift-appliance, Dockerfile.openshift-appliance-build, go.mod
handle: atomic.Pointer  module requires Go 1.19
=> MGMT-14677: Bump to go 1.19

pkg/asset/config/env_config.go
Ensures file size in cache is not zero before returning it as a valid file.
=> MGMT-14647: added file size validation on findInDir

pkg/fileutil/fileutil.go, pkg/graph/graph.go, pkg/release/release.go
SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.
=> Removed usages of deprecated io/ioutil

Makefile, hack/setup_env.sh
The version of `golangci-lint` that we are currently using is three years old. This patch updates it to the latest available version.
In addition the default timeout is one minute, and that isn't enough when it runs without a cache (which is always the case in the CI jobs):
```
$ golangci-lint cache clean
$ make lint
...
ERRO Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded
ERRO Timeout exceeded: try increasing it by passing --timeout option
```
Increasing the timeout to five minutes allows the execution to finish, and it takes approximately two minutes:
```
$ golangci-lint cache clean
$ golangci-lint run -v --timeout=5m
...
INFO Execution took 1m47.572011137s
```
This patch increases the timeout to five minutes.
=> Update golangci-lint version and timeout

README.md
We need to ensure golan version 1.19 or above is installed prior to running make build-appliance.
Otherwise the following error is thrown:
note: module requires Go 1.19
make: *** [Makefile:19: build-appliance] Error 2
=> Adding go to requirements

README.md, pkg/asset/config/appliance_config.go, pkg/asset/ignition/bootstrap_ignition.go, pkg/types/appliance_config_type.go
Added support for specifying user 'core' password on ApplianceConfig. This is required to login from console.
=> MGMT-14865: Added userCorePass to ApplianceConfig

pkg/templates/scripts/guestfish/guestfish.sh.template
The base disk image is rhcos now (instead of fedora), hence the entry item is on ostree-1-rhcos.conf.
=> MGMT-14917: Fix rhcos grub menu item removal

cmd/build.go, go.mod, go.sum, pkg/asset/ignition/recovery_ignition.go, pkg/asset/installer/installer_binary.go, pkg/installer/installer.go, pkg/release/release.go
As a last step of the build, generate and output a download URL for openshift-install binary
This is required for using the upcoming config-image API.
=> MGMT-14872: generate openshift-install download URL

pkg/asset/data/data_iso.go
Also use the word 'container' instead of 'docker'.
=> MGMT-15032: Appliance build prints should specify OCP version

pkg/asset/config/appliance_config.go
The generated ApplianceConfig template is invalid due illegal tab characters.
=> MGMT-15052: removed tabs from appliance-config template

pkg/asset/config/appliance_config.go
Minimal version of OCP release should be validated only if the version format is valid.
=> appliance-config: fix minimal release version validation

pkg/asset/config/appliance_config.go
If ocpRelease.Channel is missing in ApplianceConfig, its value should default to 'stable'.
=> MGMT-15053: fallback to stable release channel

cmd/config.go
Replaced 'at assets directory' with 'in assets directory' 
Note: build message was fixed in https://github.com/openshift/appliance/pull/52
=> MGMT-15042: fix generate-config completion message

README.md, pkg/installer/installer.go
Search for custom openshift-install binary on assets dir when using the `debug-base-ignition` flag.
This is useful for dev-scripts as the custom binary is copied to the assets dir.
=> Custom openshift-install on assets dir

docs/user-guide.md
The note is needed only on 'Access Cluster' section.
=> user-guide: remove resolvable warning from monitor section

pkg/asset/config/appliance_config.go
'podman inspect' doesn't work if the image isn't pulled yet. Hence, change validation to 'podman pull' instead.
=> fix registry uri validation

pkg/asset/config/appliance_config.go
Storing the Executer in ApplianceConfig breaks the build cmd. When running build using podman, nothing is written to assets dir. Probably some issue in asset store of the installer.
=> remove Executer from ApplianceConfig

data/scripts/bin/update-hosts.sh.template
The current indication of checking cluster's status is not good enough, mainly for multi nodes scenarios. E.g. since a cluster ready for installation doesn't mean that all workers been discovered.
Hence, changed the logic to rely on the exact number of required nodes, as specified in the start-cluster-installation script.
=> MGMT-15165: fix indication on update-hosts script

pkg/asset/config/appliance_config.go
The template is currently static, this change ensures that the template gets generated with up to date default values.
=> MGMT-15193: Refactor Config generation to use default configs

README.md, cmd/build.go, cmd/debug.go, cmd/main.go, hack/diskimage/test_install_ignition.md, pkg/asset/config/env_config.go, pkg/asset/ignition/install_ignition.go
The --debug-install flag is now redundant since a public ssh key can now be specified in the config-image (as part of install-config.yaml).
=> MGMT-15189: remove debug-install flag

hack/setup_env.sh
We don't need to install podman and genisoimage as part of openshift-appliance-build.
For now it'll be used only for running unit-tests/coverage.
=> Remove redundant install from setup_env script

Dockerfile.openshift-appliance, Makefile
https://issues.redhat.com/browse/MGMT-15235
In order to be FIPS compliant, we need to compile
all go code with CGO_ENABLED=1.
/cc @nmagnezi @filanov
=> MGMT-15235: Compile with CGO_ENABLED=1 for FIPS

Dockerfile.openshift-appliance, Dockerfile.openshift-appliance-build, Makefile
The `GO111MODULE=on` setting is the default since Go 1.16 so we can remove it and simplify the build commands.
Related: https://github.com/golang/go/issues/41330
=> Remove GO111MODULE

data/services/bootstrap/create-cluster-and-infraenv.service
The create-cluster-and-infraenv service fails on disconnected using 4.14.0-ec.3 release[*]
Hence, overridden the service and added '-v /etc/containers:/etc/containers' for propagating the registries.conf file.
Notes: 
* A proper [fix](https://github.com/openshift/installer/pull/7332) pushed to the installer for later.
* It won't affect connect environments as the registries.conf file doesn't have mirrors config by default.
[*] create-cluster-and-infraenv[2784]: level=fatal msg="Failed to register cluster with assisted-service: command 'oc adm release info -o template --template '{{.metadata.version}}' --insecure=true quay.io/openshift-release-dev/ocp-release@sha256:3c050cb52fdd3e65c518d4999d238ec026ef724503f275377fee6bf0d33093ab --registry-config=/tmp/registry-config1560177852' exited …
=> fix create-cluster-and-infraenv service on disconnected

pkg/asset/ignition/bootstrap_ignition.go
ClusterImageSet is redundant in BootstrapIgnition as it's already available as part of the unconfigured.ign.
Also, adding our custom ClusterImageSet causes a version mismtach error when using the latest config-image API (which is used in dev-scripts).
=> Removed ClusterImageSet from BootstrapIgnition

data/scripts/bin/start-local-registry.sh.template, data/services/common/start-local-registry.service, pkg/release/release.go
* Added missing images to bootstrap step.
* Added registry certificates to /etc/containers/certs.d folder.
```
NAME	  VERSION	AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.14.0-ec.3   True        False         2m      Cluster version is 4.14.0-ec.3
```
=> fix support for 4.14 cluster install

Makefile
Use --ginkgo.junit-report instead of the deprecated --ginkgo.reportFile.
=> Use ginko.junit-report in Makefile

pkg/asset/config/appliance_config.go, pkg/graph/graph.go, pkg/graph/graph_test.go, pkg/installer/installer_test.go, pkg/templates/data.go, pkg/types/appliance_config_type.go
Channel has a type of graph.ReleaseChannel, but it is currently casted as string in many places in the code for no good reason.
=> MGMT-15378: Refactor the usage of Channel to graph.ReleaseChannel

docs/user-guide.md, pkg/asset/appliance/appliance_diskimage.go, pkg/asset/config/appliance_config.go, pkg/templates/data.go, pkg/templates/partitions.go, pkg/templates/scripts/guestfish/guestfish.sh.template, pkg/types/appliance_config_type.go
* The 'diskSizeGB' property is now optional in appliance-config.yaml
* When 'diskSizeGB' is not specified, the virtual size is calcualted according to the actual content (i.e. to be as compact as possible). and the partition size is minimal.
* Added details for virt-resize usage to the use-guide.
=> Added support for cloning the appliance with virt-resize

pkg/asset/ignition/bootstrap_ignition.go
Removed redundant 'passwdUser' var declaration (shadowed the one declared on line 130).
=> Fix SSH login on bootstrap

pkg/asset/appliance/appliance_diskimage.go, pkg/templates/data.go, pkg/templates/partitions.go, pkg/templates/partitions_test.go
The root partition must be precisely calculated now as we manually create it in guestfish script.
I.e. before supporting a compact image, the root partition was resized automatically.
But now, we are giving exact start and end sectors. Thus, the partition size can be calculated according to the disk size and its content. Without this fix, the root partition size won't expand from 8GiB when specifying a disk size.
=> Calculate root partition size precisely

cmd/build.go, cmd/main.go
Created buildOpts struct in build command and moved the debug flags to it (as they are relevant only for build).
=> Move debug flags to buildOpts struct

docs/user-guide.md
Added a note about a dummy pull-secret for disconnected envs in 'Configuration Image' section.
Also, changed the section structure a bit to emphasise the steps.
=> user-guide: note about pull-secret in disconnected env

data/services/install/set-core-pass.service.template, pkg/asset/ignition/bootstrap_ignition.go, pkg/asset/ignition/install_ignition.go, pkg/templates/data.go
Added a service for setting the user core password (when specified). This is required to ensure the pass is set after reboot (i.e. as opposed to setting using the ignition).
=> MGMT-15673: set core pass on installation step

cmd/build.go
DeployConfig asset should be generate only when building the deployment ISO ('runBuildISO' func).
No need to ensure 'deployConfig' is not nil as the struct is created on 'getBuildISOCmd' func.
=> MGMT-15759: generate DeployConfig only for deployment ISO

docs/user-guide.md
Per the comments in [OSDOCS-8178](https://issues.redhat.com/browse/OSDOCS-8178), while the instructions to create and mount configuration files to an unconfigured OCP install is already in this document, it would also be helpful to add some links that point to the core OCP Agent docs as reference for the configurations available to users.
This PR adds one link (and renames the link text for another link, since that one and the link I'm adding both point to "OpenShift documentation".
=> OSDOCS-8178: linking to Agent docs for configuration reference

docs/user-guide.md
Per @danielerez's comment on #150, this PR adds another link in the user guide for configuring ZTP manifests during an Agent install.
=> OSDOCS-8178: (addendum) linking to Agent docs for configuration reference

docs/user-guide.md
Fixed 'Add custom manifests' section in user-guide. I.e. the second step has been in an incorrect location.
=> MGMT-15995: fix 'Add custom manifests' doc

docs/user-guide.md
The new oc-mirror (>=4.14) creates a CatalogSource with 'cs-' prefix when mirroring operators.
Hence, fixed the example in the user guide.
=> MGMT-16043: fix Subscription example in user-guide

cmd/clean.go, docs/user-guide.md
In order to clean the assets directory including the builder cache, the clean command now supports --cache flag. The defualt is false as the common use case for cleaning is to rebuild the appliance using data from cache.
=> MGMT-16434: added --cache flag to clean cmd

pkg/registry/registry.go
The registry data path is constructed with the working directory, which is redundant as the temp directory is already absolute (when using the openshift-appliance binary flow).
=> Fix registry data path on binary flow

pkg/asset/ignition/install_ignition.go
When 'StopLocalRegistry' is enabled in ApplianceConfig, the stop-local-registry service should be added to the install ignition. Since the service is under 'data/services/install' folder, adding its content to the install ignition.
=> MGMT-16815: add missing services to install ignition

pkg/installer/installer.go, pkg/installer/installer_test.go, pkg/release/mock_release.go, pkg/release/release.go
From recent openshift version, installer has been included in release payload. For reducing complexity, we should download installer from release payload, other than depending on another download resource.
=> Download installer binary by extract command from release payload

data/scripts/bin/stop-local-registry.sh.template
The appliance installation adds a mirroring configuration in `/etc/containers/registries.conf` to use the local registry.
If we set the option `stopLocalRegistry` to true this configuration could interfere with other pulling processes because the local registry will not be available. To avoid that situation, the mirroring configuration should be removed in this scenario.
=> MGMT-17049: Unconfigure local registry if stopLocalRegistry is set to true

Dockerfile.openshift-appliance
Changed download url of oc-mirror to stable-4.14.
This is mitigating the following  error when using a newer oc-mirror:
```
version `GLIBC_2.34' not found (required by /usr/local/bin/oc-mirror)
```
=> MGMT-17330: Use oc-mirror from stable-4.14

pkg/asset/appliance/appliance_diskimage.go, pkg/asset/ignition/install_ignition.go, pkg/consts/consts.go, pkg/templates/data.go, pkg/templates/scripts/grub/user.cfg.template
Append the content of user.cfg to grub.cfg in order to prevent duplicate menu entries. For details see:
- https://github.com/coreos/fedora-coreos-tracker/issues/805
- https://github.com/coreos/fedora-coreos-config/blob/5c1ac4e7d4a596efac69a3eb78061dc2f59e94fb/overlay.d/40grub/usr/lib/bootupd/grub2-static/configs.d/70_coreos-user.cfg
=> NO-ISSUE: Fix grub menu for 4.16

Dockerfile.openshift-appliance-build
```
go: downloading github.com/axw/gocov v1.2.1
go: github.com/axw/gocov/gocov@latest: github.com/axw/gocov@v1.2.1 requires go >= 1.22.0 (running go 1.21.13; GOTOOLCHAIN=local)
error: build error: building at STEP "RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.0 &&         go install golang.org/x/tools/cmd/goimports@v0.1.0 &&         go install github.com/onsi/ginkgo/ginkgo@v1.16.1 &&         go install github.com/golang/mock/mockgen@v1.6.0 &&         go install github.com/vektra/mockery/v2@v2.9.6 &&         go install gotest.tools/gotestsum@v1.6.3 &&         go install github.com/axw/gocov/gocov@latest &&         go install github.com/AlekSi/gocov-xml@latest": while running runtime: exit status 1
```
=> build: fix gocov failure

data/services/common/start-local-registry.service
Running the registry with '--replace' flag to ensure a proper restart on failure.
=> Ensure registry restart on failure

cmd/build.go
E.g.
```
INFO Appliance disk image was successfully created in assets directory: assets/appliance.raw 
INFO
INFO Create configuration ISO using: openshift-install agent create config-image 
INFO Copy 'openshift-install' from: assets/cache/4.18.0-rc.2-x86_64/openshift-install 
INFO Download 'openshift-install' from: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.18.0-rc.2/openshift-install-linux.tar.gz 
```
=> Include openshift-install local path on build output

data/scripts/bin/set-node-zero.sh.template, data/scripts/bin/update-hosts.sh.template, data/services/install/set-node-zero.service, pkg/asset/ignition/bootstrap_ignition.go, pkg/asset/ignition/install_ignition.go, pkg/templates/data.go
The rendezvous-host.env file is used post installation to determine which host is the rendezvous. For that, set-node-zero service and script were added.
=> MGMT-19633: Add rendezvous-host.env to install ignition

pkg/templates/data.go, pkg/templates/scripts/grub/user.cfg.template
Avoid adding 'fips=0', as it fails on OCP < 4.18
=> MGMT-19870: Fix FIPS kernel arg in grub.cfg

docs/user-guide.md
When attempting to generate the live iso, I kept coming across a fs-overlay error. After some troubleshooting, I determined that it was due to the privileged flag missing.
=> Add privileged flag to podman live iso command

cmd/build.go
Marking the debug hidden flags as PersistentFlags in order to support them in the 'build live-iso' command.
Thanks @andfasano for the fix!
=> MGMT-20132: Use PersistentFlags for debug hidden flags

data/scripts/bin/create-virtual-device.sh.template
No need for a virtual device (created from the disk image) in live ISO mode.
=> MGMT-20133: Avoid virtual device creation in live ISO mode

data/scripts/bin/update-hosts.sh.template, data/services/bootstrap/update-hosts.service
Avoid using REQUIRED_MASTER_NODES/REQUIRED_WORKER_NODES in update-hosts.sh, since these are not available when using the interactive flow.
Instead, monitor for added hosts and update the ignition, until the cluster installation is starting.
=> AGENT-1140: support interactive flow in update-hosts

data/scripts/bin/update-hosts.sh.template
This patch fixes the issue of loading the extra manifests generated by the appliance when the cluster is created by the UI. This step is necessary to ensure the correct installation of the selected OLM operators.
Requires https://github.com/openshift/appliance/pull/375
=> MGMT-20521: Load extra manifests on cluster startup

data/services/common/start-local-registry.service
For particularly big ISOs, 8 minutes could not be enough to reassembly the registry_data.iso, and the service will silently fail leaving a corrupted file
=> NO-ISSUE: Increase the start timeout to 30 min

data/services/common/start-local-registry.service
This patch allows using the ISO on real baremetal server, where the currently experienced amount of time required to reassembly the data ISO (due the BMC streaming) was about 2hrs
=> MGMT-20615: increasing local registry setup timeout to 2.5h

pkg/executer/executer.go, pkg/release/release.go
Fixed command execute func to ensure the full error output is displayed when running oc-mirror.
=> oc-mirror: output full error

docs/user-guide.md, pkg/asset/registry/registriesconf.go, pkg/release/release.go
Avoid using 'appliance.com' domain.
=> MGMT-20943: rename internal registry domain

data/scripts/bin/mount-agent-data.sh.template
In live-iso mode, the registry data is mounted from a file on disk (instead of the data partition).
This fix ensures that the data is mounted (on reboot) also after detaching the ISO.
=> OCPBUGS-61242: fix mount registry data on reboot

pkg/asset/registry/registriesconf.go, pkg/asset/registry/registriesconf_test.go
Currently the Prow CI OVE ISO jobs are permafailing due the incorrect parsing of the oc-mirror generated files. This patch fixes the issue by enabling the parsing of multi-doc yaml files for the RegistriesConf asset.
=> MGMT-21854: fix registries.conf generation for multiple yaml mirror files
