- data/scripts/bin/prepare-cluster-installation.sh.template
- pkg/asset/ignition/bootstrap_ignition.go
- pkg/asset/ignition/install_ignition.go
- pkg/templates/data.go
Add install ignition to all hosts on prepare cluster installation.
> Override ingition on prepare installation

- pkg/log/spinner.go
> MGMT-14659: Fix spinner nil pointer exception

- Dockerfile.openshift-appliance
> MGMT-14694: Container image should include skopeo

- README.md
Added a demo section and a couple of URL references.
> readme: added demo section

- Makefile
Changed default IMAGE value to quay.io/edge-infrastructure/openshift-appliance:latest
> Makefile: changed repo to edge-infrastructure

- pkg/templates/data.go
Channel name in ImageSetConfiguration should be in major.minor format. Hence, to support releases as 4.14.0-ec.2, fixed format version func.
> Fix mirror channel name for candidate releases

- Makefile
Failed on timeout a couple of times in prow.
> increase lint timeout

- cmd/clean.go
- docs/user-guide.md
- pkg/asset/appliance/appliance_diskimage.go
- pkg/asset/config/appliance_config.go
- pkg/asset/data/data_iso.go
- pkg/asset/ignition/install_ignition.go
- pkg/asset/recovery/recovery_iso.go
- pkg/consts/consts.go
- pkg/registry/registry.go
- pkg/release/release.go
- pkg/templates/data.go
- pkg/types/appliance_config_type.go
Setting will include a custom port and container image.
> MGMT-15146: Appliance config: Support a custom image registry settings

- data/scripts/bin/start-local-registry.sh.template
Ensure that the registry entry in /etc/hosts is added once.
> MGMT-15207: avoid duplicate entries in /etc/hosts

- cmd/build.go
- docs/user-guide.md
Changed build success message to:
'Appliance disk image was successfully created in assets directory:'
> MGMT-15042: changed build success message

- data/scripts/bin/pre-install-node-zero.sh.template
- data/scripts/bin/pre-install.sh.template
- data/services/bootstrap/pre-install-node-zero.service
- data/services/bootstrap/pre-install.service
- pkg/asset/ignition/bootstrap_ignition.go
The virtual device should be created on all nodes. Hence, move the creation script to a service that runs on all nodes (rather than only node zero).
> Create virtual device on all nodes to fix multi-node

- pkg/asset/config/appliance_config.go
Output user friendly error messages when failing to parse appliance-config.yaml.
E.g.
```
FATAL failed to load asset "Appliance Config": can't parse appliance-config.yaml.
Ensure the config file is configured correctly (error in field ApplianceConfig.diskSizeGb)
```
> MGMT-15170: improve errors for appliance-config unmarshal failure

- docs/user-guide.md
Added a usage example for additionalImages to the user-guide.
> MGMT-15996: added additionalImages example to the user-guide

- docs/upgrade-tool.md
This file adds the documentation for the upgrade-tool prototype
> Added documentation for upgrade-tool

- README.md
- docs/user-guide.md
* Added a note to the user-guide regarding the 'sshKey' property in install-config.yaml
* Added 'sshKey' to the install-config examples.
> docs: updates about sshKey property

- .tekton/appliance-pull-request.yaml
- .tekton/appliance-push.yaml
See: https://github.com/konflux-ci/build-definitions/blob/main/task/deprecated-image-check/0.4/MIGRATION.md
> NO-ISSUE: fix deprecated-image-check task

- data/scripts/bin/common.sh.template
- data/scripts/bin/update-hosts.sh.template
- pkg/asset/ignition/bootstrap_ignition.go
Fix installation for OCP version>=4.17
See: https://github.com/openshift/installer/pull/8393
> Added common.sh with curl wrapper

- data/scripts/bin/set-env-files.sh.template
- data/scripts/bin/update-hosts.sh.template
- pkg/asset/ignition/bootstrap_ignition.go
Following https://github.com/openshift/installer/pull/9039, added support for USER_AUTH_TOKEN env var.
> Support USER_AUTH_TOKEN

- cmd/build.go
Remove quotes from openshift-install string in build output.
> MGMT-19757: Remove quotes from build output

- pkg/asset/appliance/appliance_diskimage.go
- pkg/templates/data.go
- pkg/templates/scripts/guestfish/guestfish.sh.template
Similar to the handling in installation step:
https://github.com/openshift/appliance/blob/119839b7ed6d025c12906d5f359b2e5219a8afbc/data/scripts/bin/add-grub-menuitem.sh.template#L5
> Prevent duplicate grub items on bootstrap

- pkg/asset/data/data_iso.go
- pkg/asset/upgrade/upgrade_iso.go
- pkg/registry/registry.go
This commit resolves an issue discovered in the `upgrade-iso` subcommand. Because we changed the registry to avoid the external dependency on docker registry image, now the command fails because it cannot find the image during the workflow.
The changes has been successfully tested with a development build on a beaker environment.
* Are the title and description (in both PR and commit) meaningful and clear?
* Is there a bug required (and linked) for this change?
> MGMT-20172: Change the upgrade-iso command to remove the dependency on external registry

- registry/Dockerfile.registry
See: https://github.com/distribution/distribution/issues/4270
> Dockerfile.registry: disable exporter traces

- data/services/bootstrap/update-hosts.service
This reverts commit 15af142751797003d10643917729506818662229.
> Revert "Remove apply-host-config.service requirement"

- Dockerfile.openshift-appliance
- Dockerfile.openshift-appliance-build
- Dockerfile.openshift-appliance.ds
- go.mod
- go.sum
- registry/Dockerfile.registry
* Revert "chore(deps): update registry.access.redhat.com/ubi9/go-toolset docker tag to v9.6-1752083840"
* Revert "chore(deps): update registry.access.redhat.com/ubi9/ubi docker tag to v9.6-1751897624"
>  Revert "chore(deps): update registry.access.redhat.com/ubi9/go-toolset docker tag to v9.6-1752083840"

- .tekton/appliance-pull-request.yaml
- .tekton/appliance-push.yaml
This reverts commit e82d67e6bb25045fce0ec6dd2b93fb36b9defd52.
> Revert "Remove tekton dir"

- pkg/asset/registry/registriesconf.go
- pkg/asset/registry/registriesconf_test.go
This is a manual cherry-pick of #545
> [release-4.20] MGMT-21882: parse all the idms file entries when generating the RegistriesConf asset
